ds<-read.table("household_power_consumption.txt", header=TRUE,sep=";", stringsAsFactors=FALSE, dec=".")
d<-ds[ds$Date=="1/2/2007"|ds$Date=="2/2/2007",]
xdata<-strptime(paste(d$Date, d$Time, sep=" "),"%d/%m/%Y %H:%M:%S")
ydata<-as.numeric(as.character(d$Global_active_power))
zdata<-as.numeric(as.character(d$Global_reactive_power))
voltage<-as.numeric(as.character(d$Voltage))
SubMetering1 <- as.numeric(d$Sub_metering_1)
SubMetering2 <- as.numeric(d$Sub_metering_2)
SubMetering3 <- as.numeric(d$Sub_metering_3)
png("plot4.png", width=480, height=480)
par(mfrow = c(2, 2))
plot(xdata, ydata, type="l", xlab="", ylab="Global Active Power", cex=0.2)
plot(xdata, voltage, type="l", xlab="datetime", ylab="Voltage")
plot(xdata, SubMetering1, type="l", ylab="Energy sub metering", xlab="")
lines(xdata, SubMetering2, type="l", col="red")
lines(xdata, SubMetering3, type="l", col="blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"),lty = , bty="o", lwd=2.5, col=c("black", "red", "blue"))
plot(xdata, zdata, type="l", xlab="datetime", ylab="Global_reactive_power")
dev.off()